### ISSUE TITLE
Race during reading the r.bit

### ISSUE THREAD

**Issue by almusil** [maxamel/BitGenGo#1]
In the code there is race condition when reading the r.bit. There is currently lock only for writing to the bit. To reproduce this behavior run your tests with -race flag enabled. My suggestion is to utilize RWMutex to properly lock reading and writing operations.

**Comment by maxamel** [comment]
This is a calculated move. Random number generators are a rare case where you do not care that the data you fetched is the most up-to-date, you only care about its unpredictability. So if I fetched a bit, and someone flipped it right after me (because of a race), that's fine by me, as long as the distribution of bits is random. 
Adding a lock on read will have a performance hit. You already have a minimum threshold you have to wait between fetching bits. Having to acquire a lock will only make it worse. 
The locks on write exist to enforce a sequential setting of the bit as much as possible. Removing these locks actually degrades level of randomness.

**Comment by almusil** [comment]
I see. I had the feeling that it is intentional. Thanks for the explanation.

**Comment by maxamel** [comment]
Thanks, please refer to the "Benchmark Read/Write" section for further details.
